name: ufo_capture
description: UFO Capture - Monitor the sky, detect motion, and record anomalies
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  video_player: ^2.8.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.1.1
  wakelock_plus: ^1.1.4
  flutter_local_notifications: ^16.2.0
  in_app_purchase: ^3.1.11
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
